name: lint-brain-games

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint code
    steps:
      - uses: actions/checkout@v2
      - name: install modules
        run: make install
      - name: Run ESLint
        run: make lint
